FROM alpine:latest

RUN set -e -x && apk update && apk add net-tools arping python3 py3-pip openssh-server

COPY requirements.txt /tmp/
COPY sshd_config /etc/ssh/sshd_config
COPY ssh.sh /ssh.sh

RUN set -e -x && pip3 install --requirement /tmp/requirements.txt && \
    chmod +x /ssh.sh && \
    echo "root:root" | chpasswd

WORKDIR /usr/src/

EXPOSE 4141

CMD ["sh", "/ssh.sh"]
