version: "3.9"

services:
 
    ftp_server:
        container_name: ftp_server
        image: panubo/vsftpd:v1.0.0
        ports:
            - "21:21"
        environment:
            - FTP_USER=ftpuser
            - FTP_PASSWORD=ftppass
        volumes:
            - ./ftp_server/vsftpd:/home/vsftpd
            - ./ftp_server/log:/var/log/vsftpd
            - ./ftp_server/server:/srv
        networks:
            - inquisitor_network
    
    user:
        container_name: user
        build:
            context: .
            dockerfile: user.Dockerfile
        volumes:
            - ./home:/home:rw
        ports:
            - "4141:4141"
        networks:
            - inquisitor_network

    poison:
        container_name: poison
        build:
            context: .
            dockerfile: poison.Dockerfile
        cap_add:
            - NET_RAW
            - NET_ADMIN
        volumes:
            - ./src:/usr/src
        ports:
            - "4242:4141"
        networks:
            - inquisitor_network

networks:
    inquisitor_network:
