version: "3.9"

services:

    ftp_server:
        container_name: ftp_server
        image: fauria/vsftpd
        ports:
            - "21:21"
        environment:
            - FTP_USER=ftp_user
            - FTP_PASS=ftp_pass
        volumes:
            - ./ftp_server:/home/vsftpd
        restart: always

    user:
        container_name: user
        build:
            context: .
            dockerfile: user.Dockerfile
        volumes:
            - ./home:/home:rw
        ports:
            - "4141:4141"

    poison:
        container_name: poison
        build:
            context: .
            dockerfile: poison.Dockerfile
        cap_add:
            - NET_RAW
            - NET_ADMIN
        volumes:
            - ./src:/usr/src
        ports:
            - "4242:4141"