FROM alpine:latest

RUN set -e -x && apk update && apk add openssh-server lftp

COPY sshd_config /etc/ssh/sshd_config
COPY ssh.sh /ssh.sh

RUN set -e -x &&  chmod +x /ssh.sh && \
    echo "root:root" | chpasswd

WORKDIR /usr/src/

EXPOSE 4141

CMD ["sh", "/ssh.sh"]
