version: "3.9"
services:
  irondome:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "4240:4141"
    volumes:
      - /Users/cherrero/Documents/cursus/cyber/BootCamp_Cyber/iron_dome/inter2/log:/var/log/irondome
      - /Users/cherrero/Documents/cursus/cyber/BootCamp_Cyber/iron_dome/inter3/:/root/bootcamp/iron_dome/src:ro
      - /Users/cherrero/Documents/cursus/cyber/BootCamp_Cyber/iron_dome/inter2/:/root/bootcamp/iron_dome
    container_name: irondome5
 
